import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import { Providers } from "./providers";
import SideBar from "./components/sideBar/sideBar";
import Header from "./components/Header";
import ConnectWallet from "./components/connectWallet";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " " + "bg-gray-600 overflow-hidden"}>
        <Providers>
          {/* sideBar */}
          <section className="flex h-screen">
            <div className="">
              <SideBar />
            </div>
            <div className="w-full">
              <div className="h-16 bg-gray-900 relative flex items-center">
                <ConnectWallet />
              </div>
              <div className="w-full  h-full overflow-y-auto mt-4  p-4">
                {children}
              </div>
            </div>
          </section>
        </Providers>
      </body>
    </html>
  );
}
